# site settings

title: RhapsodicByte
description: Welcome to my portfolio website! Happy browsing :)
taglong: Thank you for visiting!
tagshort: Portfolio
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/RhapsodicByte/RhapsodicByte.github.io

# author settings

author: Bertrand Bwashi
  name: Bertrand Bwashi
  email: bbwashi@outlook.com
photo: /assets/jpg/PlaceHolder.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
